version: '3.7'

networks: 
    application:
        driver: bridge
        
services:
## Backend ##############################################
    fastify-skeleton-server:
        image: fastify-skeleton-server
        build:
            context: ../
            dockerfile: docker/Dockerfile
            target: local_dev
        volumes:
        - ../:/home/node/workdir
        ports:
            - 3000:3000
        networks:
            - application
        container_name: fastify-skeleton-server